### ISSUE TITLE
spicetify theme

### ISSUE THREAD

**Issue by jemag** [Alexrazz/dotfilesv2#1]
I see in the screenshots that you have a spicetify gruvbox theme, however I cannot find it within your dotfiles. Would it be possible to share that theme?

**Comment by 4lgn** [comment]
Yeah, of course, I already have my spicetify themes on the i3wm branch.

I can push them to the bspwm branch as well once I get home.

**Comment by jemag** [comment]
oh my bad, I should have checked on that branch too. Thank you for the answer

**Comment by 4lgn** [comment]
They are pushed to the bspwm branch now as well.

Commit: 59f0b803f8646545600f35b6bab7e29bd2e3292f
