### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by drmarwat** [Alexrazz/dotfilesv2#3]
Hello,
When I try to install I get error , should I br running these commands as root ?

$ curl -fLo /usr/local/bin/yadm https://github.com/TheLocehiliosan/yadm/raw/master/yadm && chmod a+x /usr/local/bin/yadm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132  100   132    0     0    182      0 --:--:-- --:--:-- --:--:--   182
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file /usr/local/bin/yadm: Permission denied
  1 55883    1   903    0     0    445      0  0:02:05  0:00:02  0:02:03  1153
curl: (23) Failure writing output to destination

**Comment by vnepogodin** [comment]
Yes
